# Generated by Django 5.2.5 on 2025-11-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_remove_etiquetalayout_altura_titulo_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Um nome amigável para este servidor (ex: 'Zebra da Expedição', 'Impressora da TI').", max_length=100, unique=True)),
                ('endereco_servico', models.CharField(help_text='Endereço IP e porta do serviço de impressão. Ex: http://192.168.1.50:5001', max_length=255)),
                ('api_key', models.CharField(help_text="A chave 'X-API-Key' secreta para autenticar com o serviço.", max_length=255, verbose_name='Chave de API')),
                ('nome_impressora_padrao', models.CharField(blank=True, help_text="O nome exato da impressora no Windows a ser usada por este serviço (ex: 'Zebra ZD420').", max_length=255, verbose_name='Impressora Padrão')),
                ('ativo', models.BooleanField(default=False, help_text='Define este como o servidor de impressão ativo para todas as impressões do sistema.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor de Impressão',
                'verbose_name_plural': 'Servidores de Impressão',
            },
        ),
    ]
