# Generated by Django 5.2.5 on 2025-10-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField(help_text='Intervalo de tempo entre cada solicitação.')),
            ],
        ),
    ]
