# Generated by Django 5.2.5 on 2025-11-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_interval_seconds', models.PositiveIntegerField(default=30, help_text='Tempo que o dashboard leva para buscar novos chamados. (Ex: 30)', verbose_name='Intervalo de Busca (em segundos)')),
                ('notification_sound_url', models.URLField(blank=True, default='https://example.com/sounds/default_beep.mp3', help_text='Cole a URL completa de um arquivo de áudio online (ex: .mp3, .wav)', max_length=500, verbose_name='URL do Som de Notificação')),
            ],
            options={
                'verbose_name': 'Configurações do Dashboard',
                'verbose_name_plural': 'Configurações do Dashboard',
            },
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
