# Generated by Django 5.2.5 on 2025-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_dashboardsettings_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Display (Client ID)')),
                ('channel_name', models.CharField(max_length=255, verbose_name='Canal WebSocket')),
                ('current_screen', models.CharField(choices=[('dashboard', 'Dashboard'), ('tickets', 'Tickets'), ('projects', 'Projetos'), ('remote', 'Controle Remoto')], default='tickets', max_length=50, verbose_name='Tela Atual')),
                ('available_screens', models.JSONField(default=list, verbose_name='Telas Disponíveis')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Conectado em')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Visto por último em')),
            ],
            options={
                'verbose_name': 'Display Conectado',
                'verbose_name_plural': 'Displays Conectados',
            },
        ),
    ]
