# Generated by Django 6.1 on 2026-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='control_token',
            field=models.CharField(blank=True, default='', help_text="Gerado no primeiro 'identify' deste client_id; exigido para reassumir o canal em reconexões, evitando que outra conexão sequestre o controle remoto deste display.", max_length=64, verbose_name='Token de Controle'),
        ),
    ]
