"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
DB_ENCRYPTION_KEY = os.getenv('DB_ENCRYPTION_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# os.getenv() sempre retorna string; qualquer string não-vazia (inclusive a
# literal 'False') é truthy em Python, então DEBUG precisa ser comparado
# explicitamente contra os valores que significam "ligado".
DEBUG = os.getenv('DEBUG', 'False').strip().lower() in ('true', '1', 'yes', 'on')

ALLOWED_HOSTS = ['*']

csrf_trusted = os.getenv('CSRF_TRUSTED_ORIGINS')
if not csrf_trusted:
    # Sem default: um domínio de produção hardcoded aqui mascarava a falta
    # de configuração em vez de falhar alto, e vazava o domínio real pra
    # quem lesse o código-fonte (público). Configure CSRF_TRUSTED_ORIGINS
    # no .env (ver .envexample).
    raise ImproperlyConfigured(
        "CSRF_TRUSTED_ORIGINS não está definida no .env. "
        "Defina com a(s) origem(ns) confiável(is), separadas por vírgula "
        "(ex.: https://seu-dominio.com,https://outro-dominio.com)."
    )
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted.split(',')]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


BASE_URL = os.getenv('BASE_URL')
CSP_FRAME_ANCESTORS = os.getenv('CSP_FRAME_ANCESTORS', "'self'")


# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.printer',
    'apps.panel',
    'apps.dbcom',
    'apps.reports',
    'apps.glpiintegrator',
    'channels',
]

# Em produção, é crucial usar uma camada que funcione entre processos, como o Redis.
# Em desenvolvimento, você pode usar o backend 'locmem' ou rodar uma instância local do Redis.
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = int(os.getenv('REDIS_PORT'))

CHANNEL_LAYERS = {
    "default": {
        # BACKEND para produção. Exige 'channels-redis' instalado.
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
    # "default": {
    #     # BACKEND para desenvolvimento (funciona apenas em um único processo).
    #     "BACKEND": "channels.layers.InMemoryChannelLayer"
    # }
}

ASGI_APPLICATION = 'core.asgi.application'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # AllowAdminInIframeMiddleware precisa vir ANTES do XFrameOptionsMiddleware
    # nesta lista: o processamento da resposta acontece na ordem inversa da
    # lista, então assim o XFrameOptionsMiddleware roda primeiro (define
    # X-Frame-Options: DENY por padrão) e este middleware roda depois,
    # removendo o header por último. Na ordem antiga, o X-Frame-Options
    # removido aqui era recolocado pelo XFrameOptionsMiddleware logo em
    # seguida, quebrando o embed do admin no iframe do GLPI.
    'apps.glpiintegrator.middleware.AllowAdminInIframeMiddleware', # Habilitado para permitir iframe do GLPI
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# LOGIN_REDIRECT_URL = '/admin/'
# LOGIN_URL = '/accounts/login/'
# ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Sim, use 'mysql' para MariaDB
        'NAME': os.getenv('MYSQLDB_DATABASE'),
        'USER': os.getenv('MYSQLDB_USER'),
        'PASSWORD': os.getenv('MYSQLDB_PASSWORD'),
        'HOST': os.getenv('MYSQLDB_HOST'),
        'PORT': os.getenv('MYSQLDB_PORT'),
        
        # Opções recomendadas para MariaDB
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Porto_Velho'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração de arquivos de mídia (para uploads de usuários)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# Configuração de CORS para permitir que o frontend acesse a API.
# É uma lista de "origens" (protocolo + domínio + porta) que têm permissão.
cors_allowed = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_allowed.split(',') if origin.strip()]

# IMPORTANTE: Em produção, esta opção deve ser False por segurança.
# Ela força o Django a usar a lista 'CORS_ALLOWED_ORIGINS'.
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'

# Configurações para permitir cookies dentro do iframe (cross-subdomain)
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

# Tema do Django Admin (django-unfold)
UNFOLD = {
    "SITE_TITLE": "MoreFunctionsForGLPI",
    "SITE_HEADER": "Mais Funções do GLPI",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Início"),
                "separator": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Integração GLPI"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Conexões de Banco"),
                        "icon": "database",
                        "link": reverse_lazy("admin:dbcom_externaldbconfig_changelist"),
                        "permission": lambda request: request.user.has_perm("dbcom.view_externaldbconfig"),
                    },
                    {
                        "title": _("Configuração da API GLPI"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:dbcom_glpiconfig_changelist"),
                        "permission": lambda request: request.user.has_perm("dbcom.view_glpiconfig"),
                    },
                    {
                        "title": _("Webhooks e Automação"),
                        "icon": "webhook",
                        "link": reverse_lazy("admin:dbcom_glpiwebhook_changelist"),
                        "permission": lambda request: request.user.has_perm("dbcom.view_glpiwebhook"),
                    },
                ],
            },
            {
                "title": _("Painel NOC"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Configurações do Dashboard"),
                        "icon": "tune",
                        "link": reverse_lazy("admin:panel_dashboardsettings_changelist"),
                        "permission": lambda request: request.user.has_perm("panel.view_dashboardsettings"),
                    },
                    {
                        "title": _("Displays Conectados"),
                        "icon": "desktop_windows",
                        "link": reverse_lazy("admin:panel_display_changelist"),
                        "permission": lambda request: request.user.has_perm("panel.view_display"),
                    },
                ],
            },
            {
                "title": _("Impressão de Etiquetas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Imprimir Etiquetas"),
                        "icon": "qr_code_2",
                        "link": reverse_lazy("admin_impressao_etiquetas"),
                    },
                    {
                        "title": _("Servidores de Impressão"),
                        "icon": "print",
                        "link": reverse_lazy("admin:printer_printserver_changelist"),
                        "permission": lambda request: request.user.has_perm("printer.view_printserver"),
                    },
                    {
                        "title": _("Layouts de Etiqueta"),
                        "icon": "label",
                        "link": reverse_lazy("admin:printer_etiquetalayout_changelist"),
                        "permission": lambda request: request.user.has_perm("printer.view_etiquetalayout"),
                    },
                ],
            },
            {
                "title": _("Laudos e Protocolos"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Laudos de Baixa"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:reports_laudobaixa_changelist"),
                        "permission": lambda request: request.user.has_perm("reports.view_laudobaixa"),
                    },
                    {
                        "title": _("Motivos de Baixa"),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:reports_motivobaixa_changelist"),
                        "permission": lambda request: request.user.has_perm("reports.view_motivobaixa"),
                    },
                    {
                        "title": _("Protocolos de Reparo"),
                        "icon": "handyman",
                        "link": reverse_lazy("admin:reports_protocoloreparo_changelist"),
                        "permission": lambda request: request.user.has_perm("reports.view_protocoloreparo"),
                    },
                    {
                        "title": _("Cabeçalho dos Documentos"),
                        "icon": "description",
                        "link": reverse_lazy("admin:reports_configuracaocabecalho_changelist"),
                        "permission": lambda request: request.user.has_perm("reports.view_configuracaocabecalho"),
                    },
                ],
            },
            {
                "title": _("Administração"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Usuários"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_user"),
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },
        ],
    },
}
