# Generated by Django 5.2.5 on 2025-11-16 04:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDbConfig',
            fields=[
                ('nome_conexao', models.CharField(help_text="Um nome único para esta conexão (ex: 'CRM_PRODUCAO')", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField(default=3306)),
                ('database', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração de Banco Externo',
                'verbose_name_plural': 'Configurações de Bancos Externos',
            },
        ),
        migrations.CreateModel(
            name='GLPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_api_url', models.URLField(default='https://glpi11.luffyslair.tec.br/api.php/v2', help_text='URL base da API v2 do GLPI.', max_length=255)),
                ('glpi_app_token', models.CharField(help_text="Token de Aplicação (App-Token) gerado em 'Configurar > Geral > API'.", max_length=100)),
                ('glpi_user_token', models.CharField(help_text='Token Pessoal de Acesso (User-Token) de um usuário com permissão.', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuração da Integração GLPI',
            },
        ),
        migrations.CreateModel(
            name='GLPIWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único que será usado na URL do webhook.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome descritivo (ex: Automação de Chamados de TI).', max_length=100, unique=True)),
                ('secret_key', models.CharField(blank=True, help_text='Segredo do Webhook (definido no GLPI) para validação (atualmente ignorado).', max_length=100)),
            ],
            options={
                'verbose_name': 'Webhook do GLPI',
                'verbose_name_plural': 'Webhooks do GLPI',
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo da regra (ex: Reparo de Monitor).', max_length=100)),
                ('trigger_category_id', models.PositiveIntegerField(help_text='ID da Categoria ITIL (ou Categoria PAI) que dispara esta regra.')),
                ('trigger_pending_id', models.PositiveIntegerField(help_text="ID do Status 'Pendente' (no Chamado) que inicia a ação.")),
                ('trigger_solve_ids', models.CharField(default='5', help_text='IDs dos Status (separados por vírgula, ex: 5,2) que revertem a ação.', max_length=50)),
                ('target_asset_status_on_pending', models.PositiveIntegerField(help_text="ID do Status do Ativo para definir quando 'Pendente' (ex: Em Manutenção).")),
                ('target_asset_status_on_solve', models.PositiveIntegerField(help_text="ID do Status do Ativo para definir quando 'Solucionado' (ex: Operacional).")),
                ('is_active', models.BooleanField(default=True)),
                ('webhook', models.ForeignKey(blank=True, help_text='O Webhook que acionará esta regra.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='dbcom.glpiwebhook')),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
                'unique_together': {('webhook', 'trigger_category_id')},
            },
        ),
    ]
