# Generated by Django 5.2.5 on 2025-10-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDbConfig',
            fields=[
                ('nome_conexao', models.CharField(help_text="Um nome único para esta conexão (ex: 'CRM_PRODUCAO')", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField(default=3306)),
                ('database', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(help_text='AVISO: A senha será salva em texto plano. Considere criptografar.', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração de Banco Externo',
                'verbose_name_plural': 'Configurações de Bancos Externos',
            },
        ),
    ]
