# Generated by Django 5.2.5 on 2025-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='name',
            field=models.CharField(help_text='Nome descritivo da regra (ex: Reparo de Monitor).', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='target_asset_status_on_pending',
            field=models.PositiveIntegerField(help_text="ID do Status do Ativo para definir quando 'Pendente' (ex: Em Manutenção).", verbose_name='ID do Status do Ativo (Pendente)'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='target_asset_status_on_solve',
            field=models.PositiveIntegerField(help_text="ID do Status do Ativo para definir quando 'Solucionado' (ex: Operacional).", verbose_name='ID do Status do Ativo (Solucionado)'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_category_id',
            field=models.PositiveIntegerField(help_text='ID da Categoria ITIL (ou Categoria PAI) que dispara esta regra.', verbose_name='ID da Categoria (Gatilho)'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_pending_id',
            field=models.PositiveIntegerField(help_text="ID do Status 'Pendente' (no Chamado) que inicia a ação.", verbose_name="ID do Status 'Pendente' do Chamado"),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_solve_ids',
            field=models.CharField(default='5', help_text='IDs dos Status (separados por vírgula, ex: 5,2) que revertem a ação.', max_length=50, verbose_name="IDs dos Status 'Solucionado' do Chamado"),
        ),
    ]
