# Generated by Django 5.2.5 on 2025-10-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldbconfig',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
