# Generated by Django 6.0.1 on 2026-03-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcom', '0002_alter_automationrule_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glpiconfig',
            name='glpi_status_baixa_id',
            field=models.PositiveIntegerField(blank=True, help_text="O ID do status no GLPI que será aplicado aos itens deste laudo (ex: status 'Baixado' ou 'Inativo').", null=True, verbose_name='ID do Status de Baixa (GLPI)'),
        ),
    ]
