# Generated by Django 6.1 on 2026-08-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcom', '0003_glpiconfig_glpi_status_baixa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='glpiconfig',
            name='glpi_api_v2_url',
            field=models.URLField(blank=True, help_text='URL base da API REST v2.3 do GLPI, sem sufixo de versão (ex: https://glpi11.luffyslair.tec.br/api.php).', max_length=255, verbose_name='URL Base da API v2.3'),
        ),
        migrations.AddField(
            model_name='glpiconfig',
            name='glpi_oauth_client_id',
            field=models.CharField(blank=True, help_text='Client ID do OAuthClient cadastrado no GLPI (Configurar > Geral > API > Clientes OAuth).', max_length=100, verbose_name='Client ID (OAuth)'),
        ),
        migrations.AddField(
            model_name='glpiconfig',
            name='glpi_oauth_client_secret',
            field=models.TextField(blank=True, help_text='Client Secret do OAuthClient (será salvo criptografado).', verbose_name='Client Secret (OAuth, criptografado)'),
        ),
        migrations.AddField(
            model_name='glpiconfig',
            name='glpi_oauth_password',
            field=models.TextField(blank=True, help_text='Senha da conta de serviço (será salva criptografada).', verbose_name='Senha da Conta de Serviço (criptografada)'),
        ),
        migrations.AddField(
            model_name='glpiconfig',
            name='glpi_oauth_username',
            field=models.CharField(blank=True, help_text="Login de uma conta de serviço do GLPI usada só para autenticar na API v2.3 (grant 'password').", max_length=100, verbose_name='Usuário da Conta de Serviço'),
        ),
    ]
