# Generated by Django 6.1 on 2026-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcom', '0004_glpiconfig_glpi_api_v2_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glpiwebhook',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Segredo do Webhook (definido no GLPI) usado para validar a assinatura HMAC de cada chamada. Obrigatório: sem ele, o endpoint recusa a chamada.', max_length=100),
        ),
    ]
