# Generated by Django 6.1 on 2026-08-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcom', '0005_alter_glpiwebhook_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glpiconfig',
            name='glpi_api_url',
            field=models.URLField(default='https://seu-glpi.example.com/api.php/v2', help_text='URL base da API v2 do GLPI.', max_length=255),
        ),
        migrations.AlterField(
            model_name='glpiconfig',
            name='glpi_api_v2_url',
            field=models.URLField(blank=True, help_text='URL base da API REST v2.3 do GLPI, sem sufixo de versão (ex: https://seu-glpi.example.com/api.php).', max_length=255, verbose_name='URL Base da API v2.3'),
        ),
    ]
