# Generated by Django 5.2.5 on 2025-09-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da impressora como aparece no Windows (pPrinterName).', max_length=255, unique=True)),
                ('driver', models.CharField(blank=True, help_text='Nome do driver (pDriverName).', max_length=255)),
                ('porta', models.CharField(blank=True, help_text='Porta de conexão (pPortName).', max_length=100)),
                ('localizacao', models.CharField(blank=True, help_text='Localização física (pLocation).', max_length=255)),
                ('comentario', models.TextField(blank=True, help_text='Comentários da impressora (pComment).')),
                ('status_code', models.IntegerField(blank=True, help_text='Código de status numérico do Windows (Status).', null=True)),
                ('attributes_code', models.IntegerField(blank=True, help_text='Código de atributos numérico (Attributes).', null=True)),
                ('ativa', models.BooleanField(default=True, help_text='Controle interno para habilitar ou desabilitar o uso desta impressora no sistema.')),
                ('ultima_sincronizacao', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
            },
        ),
    ]
