# Generated by Django 5.2.5 on 2025-09-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressora',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Localização física (pLocation).', max_length=255, null=True),
        ),
    ]
