# Generated by Django 5.2.5 on 2025-09-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_impressora_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressora',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentários da impressora (pComment).', null=True),
        ),
    ]
