# Generated by Django 5.2.5 on 2025-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_alter_impressora_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='selecionada_para_impressao',
            field=models.BooleanField(default=False, help_text='Marque esta opção para definir esta como a impressora padrão do sistema.'),
        ),
    ]
