# Generated by Django 5.2.5 on 2025-09-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_impressora_selecionada_para_impressao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome descritivo do layout, ex: 'Etiqueta Padrão Patrimônio 50x50mm'", max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do uso deste layout.')),
                ('largura_mm', models.FloatField(default=50, help_text='Largura da etiqueta em milímetros (mm).')),
                ('altura_mm', models.FloatField(default=50, help_text='Altura da etiqueta em milímetros (mm).')),
                ('altura_titulo_mm', models.FloatField(default=8, help_text='Altura da caixa do título em milímetros (mm).')),
                ('tamanho_fonte_titulo', models.IntegerField(default=12, help_text='Tamanho da fonte do título em pontos (pt).')),
                ('margem_vertical_qr_mm', models.FloatField(default=1, help_text='Margem vertical (acima e abaixo) do QR Code em milímetros (mm).')),
                ('arquivo_fonte', models.FileField(help_text='Arquivo da fonte .ttf (ex: ariblk.ttf). Faça o upload aqui.', upload_to='fonts/')),
                ('nome_fonte_reportlab', models.CharField(help_text="Nome a ser usado para registrar a fonte no ReportLab (ex: 'Arial-Black').", max_length=50)),
                ('padrao', models.BooleanField(default=False, help_text='Marque para definir este como o layout padrão para novas impressões.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout de Etiqueta',
                'verbose_name_plural': 'Layouts de Etiqueta',
            },
        ),
    ]
