# Generated by Django 5.2.5 on 2025-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_etiquetalayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquetalayout',
            name='altura_titulo_mm',
        ),
        migrations.RemoveField(
            model_name='etiquetalayout',
            name='margem_vertical_qr_mm',
        ),
        migrations.RemoveField(
            model_name='etiquetalayout',
            name='tamanho_fonte_titulo',
        ),
        migrations.AddField(
            model_name='etiquetalayout',
            name='layout_json',
            field=models.JSONField(blank=True, default=list, help_text='Definição JSON dos elementos do layout (gerenciado pelo editor visual).'),
        ),
    ]
