# Generated by Django 5.2.5 on 2025-11-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_printserver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impressora',
        ),
        migrations.AlterField(
            model_name='printserver',
            name='api_key',
            field=models.TextField(blank=True, help_text="A chave 'X-API-Key' secreta (será salva criptografada).", verbose_name='Chave de API (Criptografada)'),
        ),
    ]
