# Generated by Django 5.2.5 on 2025-11-10 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: M1, M2', max_length=10, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
            ],
            options={
                'verbose_name': 'Motivo de Baixa',
                'verbose_name_plural': 'Motivos de Baixa',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LaudoBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(editable=False, help_text='Gerado automaticamente ao salvar. Ex: LT-2025-001', max_length=20, unique=True, verbose_name='Nº do Documento')),
                ('data_laudo', models.DateField(default=django.utils.timezone.now, help_text='Data em que o laudo foi gerado.', verbose_name='Data do Laudo')),
                ('destinacao', models.CharField(blank=True, choices=[('DESCARTE', 'Descarte Ecológico'), ('DOACAO', 'Doação')], max_length=10, null=True, verbose_name='Destinação Recomendada')),
                ('tecnico_responsavel', models.ForeignKey(help_text='Usuário do Django que está emitindo o laudo.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Laudo de Baixa',
                'verbose_name_plural': 'Laudos de Baixa',
                'ordering': ['-numero_documento'],
            },
        ),
        migrations.CreateModel(
            name='ItemLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_id', models.IntegerField(editable=False, verbose_name='ID GLPI')),
                ('nome_equipamento', models.CharField(editable=False, max_length=255, verbose_name='Nome do Equipamento')),
                ('tipo_equipamento', models.CharField(editable=False, max_length=100, verbose_name='Tipo')),
                ('marca_equipamento', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Marca')),
                ('modelo_equipamento', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_patrimonio', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nº Patrimônio')),
                ('numero_serie', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Nº de Série')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='reports.laudobaixa', verbose_name='Laudo')),
                ('motivo_baixa', models.ForeignKey(help_text='Selecione o motivo da baixa para este item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.motivobaixa', verbose_name='Motivo da Baixa')),
            ],
            options={
                'verbose_name': 'Item do Laudo',
                'verbose_name_plural': 'Itens do Laudo',
                'unique_together': {('laudo', 'glpi_id', 'tipo_equipamento')},
            },
        ),
    ]
