# Generated by Django 5.2.5 on 2025-11-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoTecnico',
            fields=[
            ],
            options={
                'verbose_name': 'Laudo Técnico para Baixa Patrimonial',
                'verbose_name_plural': 'Laudos Técnicos para Baixa Patrimonial',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.laudobaixa',),
        ),
    ]
