# Generated by Django 5.2.5 on 2025-11-13 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_laudotecnico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloReparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(editable=False, help_text='Gerado automaticamente ao salvar. Ex: PRE-2025-001', max_length=20, unique=True, verbose_name='Nº do Documento')),
                ('data_protocolo', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Protocolo')),
                ('glpi_fornecedor_id', models.IntegerField(null=True, verbose_name='ID Fornecedor GLPI')),
                ('glpi_fornecedor_nome', models.CharField(max_length=255, null=True, verbose_name='Nome do Fornecedor')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Protocolo de Reparo',
                'verbose_name_plural': 'Protocolos de Reparo',
                'ordering': ['-numero_documento'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloReparoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Protocolo de Envio para Reparo',
                'verbose_name_plural': 'Protocolos de Envio para Reparo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.protocoloreparo',),
        ),
        migrations.CreateModel(
            name='ItemReparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_ticket_id', models.IntegerField(verbose_name='ID Ticket GLPI')),
                ('glpi_item_id', models.IntegerField(verbose_name='ID Item GLPI')),
                ('glpi_item_tipo', models.CharField(max_length=255, verbose_name='Tipo Item GLPI')),
                ('nome_item', models.CharField(max_length=255, verbose_name='Nome do Equipamento')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Série')),
                ('numero_patrimonio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Patrimônio')),
                ('titulo_ticket', models.TextField(blank=True, null=True, verbose_name='Título do Chamado')),
                ('observacao_ticket', models.TextField(blank=True, null=True, verbose_name='Observação do Chamado')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='reports.protocoloreparo', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Item de Reparo',
                'verbose_name_plural': 'Itens de Reparo',
                'unique_together': {('protocolo', 'glpi_ticket_id', 'glpi_item_id')},
            },
        ),
    ]
