# Generated by Django 5.2.5 on 2025-11-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_protocoloreparo_protocoloreparoproxy_itemreparo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCabecalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Faça upload da imagem da logo (ex: .png, .jpg)', null=True, upload_to='logos/', verbose_name='Logo da Empresa')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(help_text='Ex: 00.000.000/0001-00', max_length=18, verbose_name='CNPJ')),
                ('endereco_completo', models.CharField(help_text='Ex: Rua Exemplo, 123, Bairro, Cidade - UF, CEP 00000-000', max_length=500, verbose_name='Endereço Completo')),
            ],
            options={
                'verbose_name': 'Configuração do Cabeçalho',
                'verbose_name_plural': 'Configurações do Cabeçalho',
            },
        ),
    ]
