# Generated by Django 5.2.5 on 2025-11-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_configuracaocabecalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlaudo',
            name='motivo_baixa',
            field=models.ForeignKey(blank=True, help_text='Selecione o motivo da baixa para este item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.motivobaixa', verbose_name='Motivo da Baixa'),
        ),
    ]
