# Generated by Django 6.0.1 on 2026-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_itemlaudo_motivo_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoloreparo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', editable=False, max_length=15, verbose_name='Status'),
        ),
    ]
