# Generated by Django 6.0.1 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_protocoloreparo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudobaixa',
            name='data_baixa_glpi',
            field=models.DateTimeField(blank=True, editable=False, help_text='Preenchido automaticamente quando a ação de baixa no GLPI é concluída com sucesso.', null=True, verbose_name='Data da Baixa no GLPI'),
        ),
        migrations.AddField(
            model_name='laudobaixa',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROCESSADO', 'Processado (Baixa aplicada no GLPI)')], default='RASCUNHO', editable=False, help_text='Indica se a baixa já foi aplicada nos itens no GLPI.', max_length=15, verbose_name='Status'),
        ),
    ]
