# Generated by Django 6.1 on 2026-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_laudobaixa_data_baixa_glpi_laudobaixa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlaudo',
            name='data_processamento_glpi',
            field=models.DateTimeField(blank=True, editable=False, help_text='Quando a última tentativa de baixa deste item foi executada.', null=True, verbose_name='Data do Processamento'),
        ),
        migrations.AddField(
            model_name='itemlaudo',
            name='log_processamento_glpi',
            field=models.TextField(blank=True, editable=False, help_text='Mensagem de sucesso ou erro retornada pelo GLPI na última tentativa.', null=True, verbose_name='Log de Processamento'),
        ),
        migrations.AddField(
            model_name='itemlaudo',
            name='status_glpi',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro')], default='PENDENTE', editable=False, help_text='Resultado da última tentativa de aplicar a baixa deste item no GLPI.', max_length=15, verbose_name='Status no GLPI'),
        ),
    ]
