# Generated by Django 6.1 on 2026-08-21 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def limpar_glpi_erro_nulo(apps, schema_editor):
    ItemLaudo = apps.get_model('reports', 'ItemLaudo')
    ItemLaudo.objects.filter(glpi_erro__isnull=True).update(glpi_erro='')


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_itemlaudo_data_processamento_glpi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlaudo',
            old_name='status_glpi',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='itemlaudo',
            old_name='data_processamento_glpi',
            new_name='processado_em',
        ),
        migrations.RenameField(
            model_name='itemlaudo',
            old_name='log_processamento_glpi',
            new_name='glpi_erro',
        ),
        migrations.RunPython(limpar_glpi_erro_nulo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='itemlaudo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado no GLPI'), ('FALHA', 'Falha ao processar no GLPI')], default='PENDENTE', editable=False, max_length=15, verbose_name='Status no GLPI'),
        ),
        migrations.AlterField(
            model_name='itemlaudo',
            name='processado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Processado em'),
        ),
        migrations.AlterField(
            model_name='itemlaudo',
            name='glpi_erro',
            field=models.TextField(blank=True, editable=False, help_text='Mensagem de erro da última tentativa. Fica em branco quando o item é processado com sucesso.', verbose_name='Último Erro (GLPI)'),
        ),
        migrations.AddField(
            model_name='itemlaudo',
            name='processado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Processado por'),
        ),
    ]
