# Generated by Django 6.1 on 2026-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_itemlaudo_status_tracking_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlaudo',
            name='custom_asset',
            field=models.BooleanField(default=False, editable=False, help_text="Se marcado, 'tipo_equipamento' é o nome de um Custom Asset do GLPI (endpoint /Assets/Custom/<tipo>/<id>) em vez de um ativo nativo (endpoint /Assets/<tipo>/<id>).", verbose_name='Ativo Customizado'),
        ),
    ]
